#! /usr/bin/env ruby

require 'pg'

expenses = PG.connect(dbname: "expenses")

result = expenses.exec("SELECT * FROM expenses ORDER BY created_on;")

result.each do |tuple|
  columns = [ tuple["id"].rjust(3),
              tuple["created_on"].rjust(10),
              tuple["amount"].rjust(10),
              tuple["memo"]
            ]
  puts columns.join(" | ")
end